# version: "3.8"

# services:
#     django:
#       build: .
#       container_name: django
#       command: python manage.py runserver 0.0.0.0:8000
#       volumes:
#         - .:/app
#       ports:
#         - "8000:8000"
#       environment:
#         - DEBUG=1
#         - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1
#         - CELERY_BROKER=redis://redis:6379/0
#         - CELERY_BACKEND=redis://redis:6379/0
#         - DJANGO_SUPERUSER_USERNAME=admin
#         - DJANGO_SUPERUSER_PASSWORD=admin123
#         - DJANGO_SUPERUSER_EMAIL=admin@example.com
#       depends_on: 
#         - pgdb
#         - redis

#     celery:
#       build: .
#       # command: celery worker --app=price_comparison --loglevel=info
#       command: celery -A price_comparison worker -l info
#       volumes:
#         - ./:/app
#       depends_on:
#         - django
#         - redis
    
#     pgdb:
#       image: postgres
#       container_name: pgdb
#       environment:
#         - POSTGRES_DB=price_comparison
#         - POSTGRES_USER=dd
#         - POSTGRES_PASSWORD=password
#       ports:
#         - "5432:5432"
#       volumes:
#         - pgdata:/var/lib/postgresql/data
    
#     redis:
#       image: "redis:alpine"
# volumes:
#     pgdata:

    
version: "3.8"

services:
  django:
    build: .
    container_name: django
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1
      - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1
      - CELERY_BROKER=redis://redis:6379/0
      - CELERY_BACKEND=redis://redis:6379/0
      - DJANGO_SUPERUSER_USERNAME=admin
      - DJANGO_SUPERUSER_PASSWORD=admin123
      - DJANGO_SUPERUSER_EMAIL=admin@example.com
    depends_on:
      - pgdb
      - redis
    command: >
      sh -c "
      python manage.py makemigrations &&
      python manage.py migrate &&
      (echo 'from django.contrib.auth import get_user_model; 
      User = get_user_model(); 
      User.objects.filter(username=\"admin\").exists() or 
      User.objects.create_superuser(username=\"admin\", email=\"admin@gmail.com\", password=\"admin123\")' | python manage.py shell) &&
      python manage.py runserver 0.0.0.0:8000
      "
      
  celery:
    build: .
    command: celery -A price_comparison worker -l info
    volumes:
      - .:/app
    depends_on:
      - django
      - redis

  celery_beat:
    build: .
    command: sh -c "
      python manage.py migrate &&
      celery -A price_comparison beat -l info --scheduler django_celery_beat.schedulers:DatabaseScheduler
      "
    volumes:
      - .:/app
    depends_on:
      - pgdb
      - redis
    environment:
      - CELERY_BROKER=redis://redis:6379/0
      - CELERY_BACKEND=redis://redis:6379/0
      
  pgdb:
    image: postgres
    container_name: pgdb
    environment:
      - POSTGRES_DB=price_comparison
      - POSTGRES_USER=dd
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    
  redis:
    image: "redis:alpine"
    container_name: redis

volumes:
  pgdata:
