# version: "3.9"

# services:
#   db:
#     image: postgres:15
#     volumes:
#       - postgres_data:/var/lib/postgresql/data/
#     environment:
#       POSTGRES_DB: price_comparison
#       POSTGRES_USER: dd
#       POSTGRES_PASSWORD: password

#   redis:
#     image: redis:7
#     ports:
#       - "6379:6379"

#   web:
#     build: .
#     command: gunicorn price_comparison.wsgi:application --bind 0.0.0.0:8000
#     volumes:
#       - .:/app
#     ports:
#       - "8000:8000"
#     depends_on:
#       - db
#       - redis
#     environment:
#       - DATABASE_URL=postgres://django_user:django_pass@db:5432/price_comparison
#       - REDIS_URL=redis://redis:6379/0

#   celery_worker:
#     build: .
#     command: celery -A price_comparison worker -l info
#     volumes:
#       - .:/app
#     depends_on:
#       - db
#       - redis
#     environment:
#       - DATABASE_URL=postgres://django_user:django_pass@db:5432/price_comparison
#       - REDIS_URL=redis://redis:6379/0

#   celery_beat:
#     build: .
#     command: celery -A price_comparison beat -l info --scheduler django_celery_beat.schedulers:DatabaseScheduler
#     volumes:
#       - .:/app
#     depends_on:
#       - db
#       - redis
#     environment:
#       - DATABASE_URL=postgres://django_user:django_pass@db:5432/price_comparison
#       - REDIS_URL=redis://redis:6379/0

# volumes:
#   postgres_data:

version: "3.9"

services:
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: price_comparison
      POSTGRES_USER: dd
      POSTGRES_PASSWORD: password

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  web:
    build: .
    command: gunicorn price_comparison.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    environment:
      - DATABASE_URL=postgres://dd:password@db:5432/price_comparison
      - REDIS_URL=redis://redis:6379/0

  celery_worker:
    build: .
    command: celery -A price_comparison worker -l info
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
    environment:
      - DATABASE_URL=postgres://dd:password@db:5432/price_comparison
      - REDIS_URL=redis://redis:6379/0

  celery_beat:
    build: .
    command: celery -A price_comparison beat -l info --scheduler django_celery_beat.schedulers:DatabaseScheduler
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
    environment:
      - DATABASE_URL=postgres://dd:password@db:5432/price_comparison
      - REDIS_URL=redis://redis:6379/0

volumes:
  postgres_data:
